### ISSUE TITLE
Incorrect operand-size for IP/EIP/RIP register?

### ISSUE THREAD

**Issue by flobernd** [intelxed/xed#48]
I'm not sure if this is an actual issue, but I played with the JMP (0xE9) instruction and got the following results for the suppressed instruction-pointer operand in 32-bit mode:

`1. xed-ex1 e900000000 -> REG0=EIP SUPPRESSED  RW         V   32`
`2. xed-ex1 66e900000000 -> REG0=EIP SUPPRESSED  RW         V   16`
`3. xed-ex1 67e900000000 -> REG0=IP SUPPRESSED  RW         V   32`
`4. xed-ex1 6766e900000000 -> REG0=IP SUPPRESSED  RW         V   16`

Especially the third one looks fishy, because the operand-size is 32-bit, but the register (IP) itself is only 16-bits wide.

The Intel doc contains the following pseudo code, where EIP is always accessed as a full register (32-bit) regardless of the effective operand-size:
```
IF OperandSize = 32
  THEN
    EIP ← tempEIP;
  ELSE
    IF OperandSize = 16
      THEN (* OperandSize = 16 *)
        EIP ← tempEIP AND 0000FFFFH;
      ELSE (* OperandSize = 64)
        RIP ← tempRIP;
    FI;
FI;
```

Therefore I think the actual XED-operand-size for IP/EIP/RIP should always be the total width of the used register regardless of the effective-operand-size.

**Comment by markcharney** [comment]
acknowledged & confirmed. Will fix. Thank you for reporting this issue.

**Comment by markcharney** [comment]
I have to review a bunch of instructions that use rIP() before I push my fix. Working on this...

**Comment by markcharney** [comment]
I pushed a bunch of changes to the above branch #52 . Take a look and let me if this helps. It might need a little more work but this is a start.

**Comment by flobernd** [comment]
Looks good so far except for a little inconsistency issue regarding the operand size of the dynamic `rIP()` operands:
```
mode32:
66 e9 00 00 00 00 | REG0              REG0=EIP SUPPRESSED  RW         D   32
66 c3             | REG1              REG1=EIP SUPPRESSED   W         V   16
```
It should be 32-bits regardless of the operand-size prefix, to always match the size of the actual register (EIP).

**Comment by markcharney** [comment]
i agree. will look in to it this week. thanks.

**Comment by markcharney** [comment]
#55 failed testing so i wont put it on master br. the fails arepurely cosmetic, just requiring a rebase of tests. which i can do next week. try it out...

**Comment by flobernd** [comment]
Looks good! Only one small thing: You forgot to hardcode the reigster to `EIP` for the `0x0F 0x80` `not64` `jo` instruction.

**Comment by athre0z** [comment]
Not really related, but I thought a new issue would be a little overkill:
`INT1` aka `ICEBP` (`0xF1`) is lacking the suppressed rIP operand.

**Comment by markcharney** [comment]
thx. I'll add that to the cleanup

**Comment by markcharney** [comment]
Sorry about the delay. Pushed changes to master. Thanks for the issue(s).  Let me know if you encounter any others!
